# Site settings
paginate: 10
paginate_path: "page:num"
exclude: ["README.md"]
highlighter: rouge
markdown: kramdown
title: Will Anderson
description: RIT Computer Science Class of '23

# User settings
author:
    name: Will Anderson
    email: wsa3263@rit.edu
    github: will-a
    bio: RIT Computer Science '22

sidebar_image: /assets/20181127_161728.jpg
# sidebar_background_image: /assets/20181127_161728.jpg

BASE_PATH: